imports:
    - { resource: sonata_admin.yml }
    - { resource: ../../shared/parameters.yml }
    - { resource: ../../shared/security.yml }

sonata_page:
    ignore_route_patterns:
        - (.*)admin(.*)     # ignore admin route, ie route containing 'admin'

    ignore_uri_patterns:
        - admin(.*)         # ignore admin route, ie route containing 'admin'
