sonata_product:
    products:

    class:
        user: Application\Sonata\Userbundle\Entity\User # you must define your own user class

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataProductBundle: ~
                    SonataProductBundle: ~