sonata_notification:
    backend: sonata.notification.backend.runtime

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~