bazinga_faker:
    orm: doctrine
    locale: en_GB
    entities:
        Application\Sonata\OrderBundle\Entity\Order:
            number: 50
            custom_formatters:
                status:
                    method: randomNumber
                    parameters:
                        - 0
                        - 5
                deliveryStatus:
                    method: randomNumber
                    parameters:
                        - 0
                        - 5
                paymentStatus:
                    method: randomElement
                    parameters: [ [ 0, 1, 2, 3, 4, 9, 10, 11, 12 ] ]
                billingAddress1:
                    method: streetAddress
                billingCity:
                    method: city
                billingCountryCode:
                    method: randomElement
                    parameters:
                        - [ 'EN', 'FR' ]
                billingName:
                    method: word
                billingPhone:
                    method: phoneNumber
                billingPostcode:
                    method: postcode
                shippingAddress1:
                    method: streetAddress
                shippingCity:
                    method: city
                shippingCountryCode:
                    method: randomElement
                    parameters:
                        - [ 'EN', 'FR' ]
                shippingName:
                    method: word
                shippingPhone:
                    method: phoneNumber
                shippingPostcode:
                    method: postcode
                currency:
                    method: randomElement
                    parameters:
                        - ['EUR']
                reference:
                    method: randomNumber
                locale:
                    method: languageCode